version: "3.8"
services:
  t2s-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: t2s-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
